src/js/tab.js
src/sass/_tabs.scss

Display box-shadow at bottom of fixed tab-header, when content is scrolled

---

src/sass/_controls.scss
src/sass/_progressbar.scss
src/sass/_togglebar.scss

* Change look and feel of progress bar handle
* Delete unused media query in controlbar for icon sizes

UI enhancements 

---

src/index.html
src/sass/_base.scss
src/sass/_tabs.scss

* Reduce box-shadow in tab header when scrolling
* Optimize text rendering
* Add link to WordPress blog

Minor layout and content enhancements

---

podlove-web-player/podlove-web-player.js
podlove-web-player/static/podlove-web-player.css
podlove-web-player/static/podlove-web-player.js

Currently the skip chapter buttons are not shown if there are less than 10 chapters. This PR changes this to always show then when there are chapters.

Skip chapter buttons

---

src/examples/minimal/index.html

* Set correct path to render minimal player example

Set correct paths to minimal player example and WP testblog

---

src/sass/_buttons.scss
src/sass/_controls.scss
src/sass/_titlebar.scss
src/sass/_togglebar.scss

The play button moves to second position between image and headlines.

Titlebar layout changes

---

spec/test/timeline.spec.js
src/examples/which-format/index.html
src/index.html
src/js/app.js
src/js/controls.js
src/js/moderator.js
src/js/modules/chapter.js
src/js/modules/progressbar.js
src/js/modules/savetime.js
src/js/player.js
src/js/social-button-list.js
src/js/social-network.js
src/js/timeline.js
src/static.html

If duration is not given, wait for the source file metadata to be loaded before rendering modules.

No duration fallback

---

src/examples/which-format/index.html
src/js/modules/progressbar.js

see https://trello.com/c/M70DjZ7U/144-progressbar-fixen for details

Better Progress bar

---

src/js/app.js

Whenever a player has focus following keyboard commands can be used
space - pause/play
left - 1s skip
right - -1s skip
up - next chapter
down - previous chapter
:warning: needs testing: more than one player embedded in one page

add basic keyboard controls

---

.gitignore
src/sass/_controlbar.scss
src/sass/_togglebar.scss
src/sass/_type.scss

* Align tab icons irrespective of their amount
* Break long words/links in tabs

Fix tab layout

---

src/sass/_titlebar.scss
src/sass/_variables.scss

to stress boundaries between image and body background-color for
embedded players for the likely case, the image has the same color as
the background of the site.

Create space between episode image and player border

---

src/js/modules/share.js
src/js/social-button-list.js
src/sass/modules/_share.scss

Delete image blocks from layout.
Convert share list into a clean & simple radio option list

Simplify Share Tab

---

src/examples/cre-206/index.html
src/examples/injected/index.html
src/examples/minimal/index.html
src/examples/picture-stream/index.html
src/examples/themes/blue-orange/index.html
src/examples/themes/creamy/index.html
src/examples/themes/dark-blaze/index.html
src/examples/themes/dark-gray/index.html
src/examples/themes/dark-green/index.html
src/examples/themes/dark/index.html
src/examples/themes/jungle-green/index.html
src/examples/themes/light-gray/index.html
src/examples/themes/light/index.html
src/examples/themes/midnightblue/index.html
src/examples/themes/silver-blaze/index.html
src/examples/themes/silver/index.html
src/examples/which-format/index.html
src/js/modules/info.js
src/js/social-networks.js
src/sass/_main.scss
src/sass/_social-network.scss
src/sass/_social-profiles.scss
src/sass/_tabs.scss
src/sass/modules/_info.scss

* Add social profiles to player examples
* Refactor SCSS files for profiles
* Fix layout for social profiles

Fix social profiles

---

bower.json
gulpfile.js
package.json

as requested here: https://trello.com/c/eEYjSeVn/174-browsersync-entfernen
also removed a syntax error in the `bower.json`

removed browser-sync, issues with js refresh because of time-sensitivity

---

src/sass/_titlebar.scss

- fixed bug with flexbox on header (added fixed width)
- removed fixed width of cover-image

fixed bug on mobile safari with responsiveness width

---

src/js/modules/info.js

Previously the info tab would only render if a summary was given.

render info tab without summary

---

src/js/modules/downloads.js
src/sass/_footer.scss
src/sass/_main.scss
src/sass/_tabs.scss
src/sass/modules/_info.scss
src/sass/modules/_share.scss

Refactor tab-footer stylings:
- create new css file for tab-footer stylings
- override footer stylings for info tab only
- extract tab-footer stylings from all tabs into one file
The functionality of the input has to be fixed!
@line-o Please have a look on this.
Fixes https://trello.com/c/tSBew6Ud

Download tab: Create footer with input for media link

---

src/js/app.js
src/js/modules/chapter.js
src/js/modules/info.js

You only need to load metadata, if you don't have an duration 
See https://trello.com/c/yliQMSUs and the slack discussion in #publisher on 28. Jan 2016

only load metadata, if you don't have an duration

---

package.json
src/app.js
src/components/info/Info.vue
src/components/player/Player.vue
src/components/tabs/settings/Settings.vue
src/embed/embed.js
src/store/reducers/chapters.js
src/store/reducers/init.js
src/utils/debug.js

- Share button only visible if needed reference available
- Player version now visible and included in debug state
- Fallback for missing chapters
- Don’t display image if no poster is provided

fix(publisher-integration): Several adaptions for web player integration

---

src/components/icons/AudioIcon.vue
src/components/icons/MinusIcon.vue
src/components/icons/PlusIcon.vue
src/components/player/control-bar/ControlBar.vue
src/components/tabs/Tabs.vue
src/components/tabs/audio/AudioRate.vue
src/components/tabs/audio/AudioVolume.vue
src/components/tabs/chapters/ChapterEntry.vue
src/components/tabs/share/ShareEmbed.vue
src/store/reducers/player.js
src/store/reducers/player.test.js
src/utils/time.js
src/utils/time.test.js

refactor(responsive): Fix bug in medium sized chapters player

---

CONTRIBUTION.md
circle.yml
docs/Gemfile
docs/Gemfile.lock
docs/embedding.md
docs/index.md
docs/persistence.md
docs/playground.md
package.json
src/components/header/Info.vue
src/components/icons/AudioIcon.vue

- Update docs system
- Add references to old docs

fix(header): Enable truncation for title, subtile and description

---

docs/advanced.md
src/store/reducers/share.js
src/store/reducers/share.test.js

- Set epsiode as default share channel

chore(docs): Update docs with actions

---

src/components/tabs/transcripts/Render.vue
src/lang/de.json
src/lang/en.json
src/store/reducers/theme.js

- Adapts title
- Increases active chapter background

fix(transcripts): Fixes scroll bug

---

src/app.js
src/components/tabs/Tabs.vue
src/components/tabs/transcripts/Render.vue
src/effects/index.js
src/effects/transcripts/fetch.js
src/effects/transcripts/fetch.test.js
src/effects/transcripts/fixtures.js

- Splits transcripts now after 500 characters
- Improved transcript generation
- Moves transcripts tab closer to chapters
- Fixes a bug that prevents player reinitialisation

fix(transcripts): Single Speaker

---

package.json
yarn.lock

fix(package): update vue to version 2.5.16

---

package.json

chore(package): update vue-loader to version 15.2.1

---

package.json

fix(package): update redux-actions to version 2.4.0

---

package.json

chore(package): update lolex to version 2.7.0

---

package.json

chore(package): update webpack-bundle-analyzer to version 2.13.1

---

package.json

chore(package): update vue-loader to version 15.2.4

---

package.json

chore(package): update sass-loader to version 7.0.3

---

build/webpack.config.base.js
build/webpack.config.prod.js
src/embed/embed.js

- Version is now also included in debug output

fix(embedding): Adds version to file requests

---

cypress/integration/tab-audio.spec.js
src/components/shared/InputSlider.vue
src/components/tabs/audio/AudioRate.vue
src/components/tabs/audio/AudioVolume.vue

Audiotab double click

---

package.json

chore(package): update webpack to version 4.16.4

---

package.json

chore(package): update autoprefixer to version 9.1.0

---

package.json

chore(package): update vue-loader to version 15.2.6

---

package.json

fix(package): update redux-actions to version 2.6.1

---

package.json

chore(package): update cypress to version 3.1.0

---

package.json

chore(package): update vue-loader to version 15.4.0

---

package.json

chore(package): update compression-webpack-plugin to version 2.0.0

---

package.json
src/components/tabs/share/channels/ChannelFacebook.vue
src/components/tabs/share/channels/ChannelGooglePlus.vue
src/components/tabs/share/channels/ChannelMail.vue
src/components/tabs/share/channels/ChannelPinterest.vue
src/components/tabs/share/channels/ChannelReddit.vue
src/components/tabs/share/channels/ChannelTwitter.vue
src/components/tabs/transcripts/Entry.vue
src/effects/player.test.js
src/effects/transcripts/active.js
src/utils/chapters.js
src/utils/dom.test.js
src/utils/storage.js
src/utils/storage.test.js
src/utils/time.js
src/utils/url.js
yarn.lock

chore(package): update standard to version 12.0.1

---

src/lang/de.json
src/lang/en.json
src/lang/eo.json

and some typos in other translations

Update Esperanto translation
